// This script runs during Vercel's build step.
// It reads environment variables from process.env (set in Vercel dashboard)
// and writes them into a static JS file that the Flutter app loads at runtime.

const fs = require('fs');
const path = require('path');

const envConfig = {
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || '',
  OPENAI_BASE_URL: process.env.OPENAI_BASE_URL || 'https://openrouter.ai/api/v1',
  CHAT_MODEL: process.env.CHAT_MODEL || 'gpt-5.4-mini',
  FEEDBACK_MODEL: process.env.FEEDBACK_MODEL || 'gpt-5.4-mini',
  AUDIO_API_KEY: process.env.AUDIO_API_KEY || '',
  AUDIO_BASE_URL: process.env.AUDIO_BASE_URL || 'https://api.openai.com/v1',
  GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
  GEMINI_BASE_URL: process.env.GEMINI_BASE_URL || 'https://generative.googleapis.com/v1',
  API_PROVIDER: process.env.API_PROVIDER || 'openai',
  WHISPER_MODEL: process.env.WHISPER_MODEL || 'whisper-1',
  TTS_MODEL: process.env.TTS_MODEL || 'tts-1',
};

const outputPath = path.join(__dirname, 'build', 'web', 'env_config.js');
const jsContent = `// Auto-generated by generate_env.js at build time\nwindow._flutterEnv = ${JSON.stringify(envConfig, null, 2)};\n`;

fs.writeFileSync(outputPath, jsContent);
console.log('[RealTalk] Generated env_config.js with keys:', Object.keys(envConfig).join(', '));
